container:
  image: ubuntu:bionic

task:
  matrix:
    - name: Build on Ubuntu (gcc, release)
      install_dependencies_script:
        - apt-get update
        - apt-get install -y cmake gcc g++
      script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release
      container:
        matrix:
          - image: ubuntu:20.04
          - image: ubuntu:16.04
          - image: ubuntu:18.04
    - name: Build on Ubuntu (gcc, debug)
      install_dependencies_script:
        - apt-get update
        - apt-get install -y cmake gcc g++
      script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Debug
      container:
        matrix:
          - image: ubuntu:20.04
          - image: ubuntu:16.04
          - image: ubuntu:18.04
    - name: Build on CentOS (gcc, release)
      install_dependencies_script:
        - yum install -y make gcc gcc-c++
      script: /ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release
      container:
        matrix:
          - image: centos:7
          - image: centos:8
    - name: Build on CentOS (gcc, debug)
      install_dependencies_script:
        - yum install -y make gcc gcc-c++
      script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Debug
      container:
        matrix:
          - image: centos:7
          - image: centos:8
    - name: Build on FreeBSD (debug)
      install_dependencies_script:
        - pkg install -y cmake gmake
      script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Debug
      freebsd_instance:
        matrix:
          #- image: freebsd-12-1-release-amd64
          - image: freebsd-11-4-release-amd64
    - name: Build on FreeBSD (release)
      install_dependencies_script:
        - pkg install -y cmake gmake
      script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release
      freebsd_instance:
        matrix:
          #- image: freebsd-12-1-release-amd64
          - image: freebsd-11-4-release-amd64
